#! /bin/sh
picom --experimental-backends & # Compositor
~/.config/polybar/launch.sh & # Status bar
xsetroot -cursor_name left_ptr & # X cursor fix
dunst & # Notifications
feh --bg-fill ~/Pictures/Wallpapers/space-neon.jpg & # Wallpaper
sxhkd & # Keyboard shortcuts
xss-lock -- betterlockscreen -l -t "SGVsbG8sIGN1cmlvdXMgb25l" & # Lockscreen handler

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config focus_follows_pointer true

# bspc config single_monocle	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
